title: Tony's blog
author:
  name: Tony
  email: 

description: >
  Hello, github blog!

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

header_pages:
  - about.md
